## Clean Oscars Data

In [47]:
import pandas as pd 

# read data
oscars = pd.read_csv('oscars.csv', sep='\t')

oscars

,Ceremony,Year,Class,CanonicalCategory,Category,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Noose|The Patent Leather Kid,tt0019217|tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,NaN,Nickie Elkins|The Patent Leather Kid,NaN,NaN
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Last Command|The Way of All Flesh,tt0019071|tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexand...,NaN,NaN
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,NaN,Mrs. Pleznik,NaN,NaN
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,7th Heaven|Street Angel|Sunrise,tt0018379|tt0019429|tt0018455,Janet Gaynor,Janet Gaynor,nm0310980,True,Diane|Angela|The Wife,NaN,NaN
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Sadie Thompson,tt0019344,Gloria Swanson,Gloria Swanson,nm0841797,NaN,Sadie Thompson,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12113,98,2025,Writing,WRITING (Original Screenplay),Writing (Original Screenplay),Blue Moon,tt32536315,Written by Robert Kaplow,Robert Kaplow,nm2904878,NaN,NaN,NaN,NaN
12114,98,2025,Writing,WRITING (Original Screenplay),Writing (Original Screenplay),It Was Just an Accident,tt36491653,Written by Jafar Panahi; Script collaborators ...,Jafar Panahi|Script collaborators - Nader Saïv...,nm0070159|nm18145787|nm2158640|nm18145788,NaN,NaN,NaN,NaN
12115,98,2025,Writing,WRITING (Original Screenplay),Writing (Original Screenplay),Marty Supreme,tt32916440,Written by Ronald Bronstein & Josh Safdie,Ronald Bronstein|Josh Safdie,?|nm1343394,NaN,NaN,NaN,NaN
12116,98,2025,Writing,WRITING (Original Screenplay),Writing (Original Screenplay),Sentimental Value,tt27714581,"Written by Eskil Vogt, Joachim Trier",Eskil Vogt|Joachim Trier,nm1258777|nm1258686,NaN,NaN,NaN,NaN
12117,98,2025,Writing,WRITING (Original Screenplay),Writing (Original Screenplay),Sinners,tt31193180,Written by Ryan Coogler,Ryan Coogler,nm3363032,NaN,NaN,NaN,NaN

In [48]:
# filter to only 2011 to 2025
oscars = oscars[oscars['Year'].isin(['2011', '2012', '2013','2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'])]

In [49]:
# Films missing IMDB ID 
# TODO - Fix any film that needs IMDB ID
no_film_id = oscars[oscars['FilmId'].isna()]
no_film_id

,Ceremony,Year,Class,CanonicalCategory,Category,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
10198,84,2011,Special,JEAN HERSHOLT HUMANITARIAN AWARD,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,Oprah Winfrey,Oprah Winfrey,nm0001856,True,NaN,NaN,NaN
10199,84,2011,Special,HONORARY AWARD,HONORARY AWARD,NaN,NaN,NaN,James Earl Jones,nm0000469,True,NaN,NaN,To James Earl Jones for his legacy of consiste...
10200,84,2011,Special,HONORARY AWARD,HONORARY AWARD,NaN,NaN,NaN,Dick Smith,nm0004615,True,NaN,NaN,To Dick Smith for his unparalleled mastery of ...
10201,84,2011,Special,GORDON E. SAWYER AWARD,GORDON E. SAWYER AWARD,NaN,NaN,NaN,Douglas Trumbull,nm0874320,True,NaN,NaN,Douglas Trumbull
10202,84,2011,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Academy Award ...,SCIENTIFIC AND TECHNICAL AWARD (Academy Award ...,NaN,NaN,NaN,Franz Kraus|Johannes Steurer|Wolfgang Riedel,nm0470117|?|?,True,Special Photographic,The ARRILASER film recorder demonstrates a hig...,"To FRANZ KRAUS, JOHANNES STEURER and WOLFGANG ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11989,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Attila T. Áfra|Timo Aila,NaN,True,NaN,Open Image Denoise is an open-source library t...,To ATTILA T. ÁFRA for the creation of Intel Op...
11990,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Mark Noel,NaN,True,NaN,The NACMO series of modular motion bases enabl...,To MARK NOEL for adapting and enhancing the sa...
11991,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Su Tie|Bei Shimen|Zhao Yanchong,NaN,True,NaN,Utilizing three-axis stabilization through mul...,To SU TIE for the development of the sensor an...
11992,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Tabb Firchau|John Ellison|Steve Webb|David Blo...,NaN,True,NaN,Freefly Systems' introduction of handheld stab...,To TABB FIRCHAU for the conception and develop...
12079,98,2025,Music,MUSIC (Original Song),Music (Original Song),KPop Demon Hunters,NaN,Music,Music,NaN,NaN,Golden,NaN,NaN

In [52]:
# these are all the categories
print(oscars.Category.unique())

['ACTOR IN A LEADING ROLE' 'ACTOR IN A SUPPORTING ROLE'
 'ACTRESS IN A LEADING ROLE' 'ACTRESS IN A SUPPORTING ROLE'
 'ANIMATED FEATURE FILM' 'ART DIRECTION' 'CINEMATOGRAPHY' 'COSTUME DESIGN'
 'DIRECTING' 'DOCUMENTARY (Feature)' 'DOCUMENTARY (Short Subject)'
 'FILM EDITING' 'FOREIGN LANGUAGE FILM' 'MAKEUP' 'MUSIC (Original Score)'
 'MUSIC (Original Song)' 'BEST PICTURE' 'SHORT FILM (Animated)'
 'SHORT FILM (Live Action)' 'SOUND EDITING' 'SOUND MIXING'
 'VISUAL EFFECTS' 'WRITING (Adapted Screenplay)'
 'WRITING (Original Screenplay)' 'JEAN HERSHOLT HUMANITARIAN AWARD'
 'HONORARY AWARD' 'GORDON E. SAWYER AWARD'
 'SCIENTIFIC AND TECHNICAL AWARD (Academy Award of Merit)'
 'SCIENTIFIC AND TECHNICAL AWARD (Scientific and Engineering Award)'
 'SCIENTIFIC AND TECHNICAL AWARD (Technical Achievement Award)'
 'JOHN A. BONNER MEDAL OF COMMENDATION' 'MAKEUP AND HAIRSTYLING'
 'PRODUCTION DESIGN' 'AWARD OF COMMENDATION'
 'SCIENTIFIC AND TECHNICAL AWARD (Special Award)' 'SPECIAL AWARD'
 'IRVING G. THALBERG MEMORIAL AWARD' 'INTERNATIONAL FEATURE FILM' 'SOUND'
 'DOCUMENTARY FEATURE FILM' 'DOCUMENTARY SHORT FILM' 'ANIMATED SHORT FILM'
 'Actor in a Leading Role' 'Actor in a Supporting Role'
 'Actress in a Leading Role' 'Actress in a Supporting Role'
 'Animated Feature Film' 'Animated Short Film' 'Casting' 'Cinematography'
 'Costume Design' 'Directing' 'Documentary Feature Film'
 'Documentary Short Film' 'Film Editing' 'International Feature Film'
 'Live Action Short Film' 'Makeup and Hairstyling'
 'Music (Original Score)' 'Music (Original Song)' 'Best Picture'
 'Production Design' 'Sound' 'Visual Effects'
 'Writing (Adapted Screenplay)' 'Writing (Original Screenplay)']

In [ ]:
# these are the categories for films missing IMDB ID 
no_film_id_categories = no_film_id.Category.unique()
print(no_film_id_categories)

**👉 Task: Come up with reasoning to exclude these and then remove them**

**👉 Remove Columns You Don't Need

## Clean Film Festivals Data

**👉 Task: Remove columns you don\'t need**

**👉 Task: Merge Manually Collected Data**

# Merge Data

**👉 Task: Merge two datasets so you only have the rows and columns you need**