In [1]:
import pandas as pd

In [2]:
pd.read_csv('combined_film_oscars.csv')

/var/folders/j5/twx6v7jj4nq17ymrbt5c1klw0000gn/T/ipykernel_89176/99386385.py:1: DtypeWarning: Columns (16,42,43,44,45,46,47,48,49,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('combined_film_oscars.csv')

,film.id,unique.id,sample.year,fest,fest.sect,imdb.id,title.mixed,prod.year,length.min,length,...,Category,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
0,f2081,1,2013,CANNES,Cannes Classics - Documentaries About Cinema,tt2917506,a story of children and film,2013.0,101.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tffnew391,10,2012,TIFF,discovery: 2012,tt2852460,bends,2013.0,96.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,f2023,10,2013,CANNES,Un Certain Regard,tt2852460,bends,2013.0,96.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f1160,100,2013,BERLINALE,Forum,tt0057494,a legend or was it?,1963.0,83.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,f1285,1000,2013,BERLINALE,Retrospective,tt0032445,somewhere in the netherlands,1940.0,86.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10374,tffnew95,tffnew95,2011,TIFF,special presentation: 2011,tt1720616,friends with kids,2011.0,107.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10375,tffnew96,tffnew96,2011,TIFF,gala presentation: opening night: 2011,tt2007385,from the sky down,2011.0,90.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10376,tffnew97,tffnew97,2011,TIFF,contemporary world cinema: 2011,tt2033997,gelecek uzun surer,2011.0,108.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10377,tffnew98,tffnew98,2011,TIFF,vanguard: 2011,tt0459748,"generation ""?""",2011.0,112.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10378,tffnew99,tffnew99,2011,TIFF,real to reel: 2011,tt1982113,gerhard richter painting,2011.0,97.0,41 min. or longer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.read_csv('oscars_2019.csv')

,Ceremony,Year,Class,CanonicalCategory,Category,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
0,92,2019,Acting,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,Pain and Glory,tt8291806,Antonio Banderas,Antonio Banderas,nm0000104,NaN,Salvador,NaN,NaN
1,92,2019,Acting,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,Once upon a Time...in Hollywood,tt7131622,Leonardo DiCaprio,Leonardo DiCaprio,nm0000138,NaN,Rick Dalton,NaN,NaN
2,92,2019,Acting,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,Marriage Story,tt7653254,Adam Driver,Adam Driver,nm3485845,NaN,Charlie Barber,NaN,NaN
3,92,2019,Acting,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,Joker,tt7286456,Joaquin Phoenix,Joaquin Phoenix,nm0001618,True,Arthur Fleck,NaN,NaN
4,92,2019,Acting,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,The Two Popes,tt8404614,Jonathan Pryce,Jonathan Pryce,nm0000596,NaN,Cardinal Jorge Bergoglio/Pope Francis,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,92,2019,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Niall Ryan|Christoph Sprenger|Gilles Daviet,nm2915743|nm1587248|nm5523902,True,NaN,The Synapse Hair Simulation System is a robust...,"To NIALL RYAN, CHRISTOPH SPRENGER and GILLES D..."
141,92,2019,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Jens-Jørn Stokholm|Ole Moesmann,NaN,True,NaN,The DPA 4061 and 4071 lavalier microphones exe...,To JENS-JØRN STOKHOLM and OLE MOESMANN for the...
142,92,2019,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Chris Countryman|Omer T. Inan,NaN,True,NaN,Originated by company founder Carl Countryman ...,To CHRIS COUNTRYMAN and OMER T. INAN for their...
143,92,2019,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Fredrik Limsäter|Björn Rydahl|Mattias Lagergren,NaN,True,NaN,"An extensible, efficient and intuitive post-pr...","To FREDRIK LIMSÄTER, BJÖRN RYDAHL and MATTIAS ..."
144,92,2019,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,Don Parker|Matt Daw|Isaac Reuben|Colin Withers...,NaN,True,NaN,"An extensible, web-based, flexible and scalabl...",To DON PARKER for the product vision and desig...